weapon_info_dict = {"subs" : {"Auto Bombs" : [
                                                "Custom Splattershot Jr.", 
                                                "N-Zap 89", 
                                                "Custom Blaster", 
                                                "Carbon Roller", 
                                                "Octobrush", 
                                                "Herobrush Replica", 
                                                "New Squiffer", 
                                                "Sloshing Machine", 
                                                "Hydra Splatling", 
                                                "Dark Tetra Dualies", 
                                                "Sorella Brella"
                                                ],
                                  "Burst Bombs" : [
                                                  "Splattershot",
                                                  "Hero Shot Replica",
                                                  "Neo Splash-o-matic",
                                                  "Aerospray PG",
                                                  "Custom Jet Squelcher",
                                                  "L-3 Nozzlenose D",
                                                  "Grim Range Blaster",
                                                  "Carbon Roller Deco",
                                                  "Tri-Slosher",
                                                  "Mini Splatling",
                                                  "Splat Dualies",
                                                  "Hero Dualies Replicas"
                                                  ],
                                  "Curling Bombs" : [
                                                    ".52 Gal Deco",
                                                    "L-3 Nozzlenose",
                                                    "Sploosh-o-matic",
                                                    "Clash Blaster Neo",
                                                    "Custom Range Blaster",
                                                    "Splat Roller",
                                                    "Hero Roller Replica",
                                                    "Custom Goo Tuber",
                                                    "Bamboozler 14 Mk 1",
                                                    "Zink Mini Splatling",
                                                    "Enperry Splat Dualies"
                                                    ],
                                  "Ink Mines" : [
                                                "Rapid Blaster",
                                                "Luna Blaster Neo",
                                                "Dynamo Roller",
                                                "Inkbrush Nouveau",
                                                "E-liter 4K",
                                                "E-liter 4K Scope",
                                                "Custom Hydra Splatling",
                                                "Glooga Dualies",
                                                "Tenta Camo Brella",
                                                "Undercover Brella"
                                                ],
                                  "Fizzy Bombs" : [
                                                  "Kensa Luna Blaster",
                                                  "Bamboozler 14 Mk 3",
                                                  "Kensa Sloshing Machine",
                                                  "Kensa Glooga Dualies"
                                                  ],
                                  "Point Sensors" : [
                                                    "Splattershot Pro",
                                                    ".52 Gal",
                                                    "H-3 Nozzlenose",
                                                    "Classic Squiffer",
                                                    "Sloshing Machine Neo",
                                                    "Custom Explosher",
                                                    "Heavy Splatling Remix",
                                                    "Nautilus 47",
                                                    "Dualie Squelchers"
                                                  ],
                                  "Splash Walls" : [
                                                  "Kensa .52 Gal",
                                                  "Kensa L-3 Nozzlenose",
                                                  ".96 Gal Deco",
                                                  "Cherry H-3 Nozzlenose",
                                                  "Squeezer",
                                                  "Rapid Blaster Pro Deco",
                                                  "Flingza Roller",
                                                  "Firefin Splat Charger",
                                                  "Firefin Splattercope",
                                                  "Bloblobber",
                                                  "Heavy Splatling Deco",
                                                  "Glooga Dualies Deco",
                                                  "Tenta Sorella Brella"
                                                  ],
                                  "Splat Bombs" : [
                                                  "Tentatek Splattershot",
                                                  "Octo Shot Replica",
                                                  "Kensa Splattershot Pro",
                                                  "Splattershot Jr.",
                                                  "Sploosh-o-matic 7",
                                                  "Foil Squeezer",
                                                  "Luna Blaster",
                                                  "Clash Blaster",
                                                  "Kensa Splat Roller",
                                                  "Gold Dynamo Roller",
                                                  "Inkbrush",
                                                  "Splat Charger",
                                                  "Splatterscope",
                                                  "Hero Charger Replica",
                                                  "Soda Slosher",
                                                  "Tri-Slosher Nouveau",
                                                  "Custom Dualie Squelchers",
                                                  "Undercover Sorella Brella"
                                                 ],
                                  "Sprinklers" : [
                                                 "Aerospray RG",
                                                 "N-Zap 83",
                                                 ".96 Gal",
                                                 "Kensa Dynamo Roller",
                                                 "Permanent Inkbrush",
                                                 "Kensa Charger",
                                                 "Kensa Splatterscope",
                                                 "Slosher Deco",
                                                 "Explosher",
                                                 "Bloblobber Deco",
                                                 "Heavy Splatling",
                                                 "Hero Splatling Replica",
                                                 "Light Tetra Dualies",
                                                 "Splat Brella",
                                                 "Hero Brella Replica"
                                                ],
                                  "Squid Beakons" : [
                                                    "Neo Sploosh-o-matic",
                                                    "Krak-On Splat Roller",
                                                    "Octobrush Nouveau",
                                                    "Custom E-liter 4K",
                                                    "Custom E-liter 4K Scope",
                                                    "Ballpoint Splatling Nouveau",
                                                    "Dapple Dualies",
                                                    "Tenta Brella" 
                                                  ],
                                  "Suction Bombs" : [
                                                    "Kensa Splattershot",
                                                    "Forge Splattershot Pro",
                                                    "Aerospray MG",
                                                    "N-Zap 85",
                                                    "H-3 Nozzlenose D",
                                                    "Rapid Blaster Deco",
                                                    "Range Blaster",
                                                    "Foil Flingza Roller",
                                                    "Kensa Octobrush",
                                                    "Goo Tuber",
                                                    "Fresh Squiffer",
                                                    "Slosher",
                                                    "Hero Slosher Replica",
                                                    "Nautilus 79",
                                                    "Kensa Splat Dualies"
                                                  ],
                                  "Torpedos" : [
                                              "Kensa Splattershot Jr.",
                                              "Kensa Rapid Blaster",
                                              "Clear Dapple Dualies",
                                              "Kensa Undercover Brella"
                                              ],
                                  "Toxic Mist" : [
                                                 "Splash-o-matic",
                                                 "Jet Squelcher",
                                                 "Blaster",
                                                 "Hero Blaster Replica",
                                                 "Rapid Blaster Pro",
                                                 "Bamboozler 14 Mk 2",
                                                 "Kensa Mini Splatling",
                                                 "Ballpoint Splatling",
                                                 "Dapple Dualies Nouveau"
                                                 ]
                                }, 
                        "specials" : {"Baller" : [
                                                  "Aerospray RG",
                                                  ".52 Gal",
                                                  "L-3 Nozzlenose",
                                                  "Kensa Rapid Blaster",
                                                  "Luna Blaster",
                                                  "Krak-On Splat Roller",
                                                  "Inkbrush Nouveau",
                                                  "Kensa Charger",
                                                  "Kensa Splatterscope",
                                                  "New Squiffer",
                                                  "Slosher Deco",
                                                  "Custom Explosher",
                                                  "Nautilus 47",
                                                  "Kensa Splat Dualies",
                                                  "Glooga Dualies Deco",
                                                  "Undercover Sorella Brella"
                                                 ],
                                      "Bomb Launcher" : [
                                                         "Neo Splash-o-matic",
                                                         "Aerospray MG",
                                                         "Rapid Blaster",
                                                         "Luna Blaster Neo",
                                                         "Carbon Roller Deco",
                                                         "Flingza Roller",
                                                         "Firefin Splat Charger",
                                                         "Firefin Splatterscope",
                                                         "Bamboozler 14Mk 2",
                                                         "Soda Slosher",
                                                         "Sloshing Machine Neo",
                                                         "Bloblobber Deco",
                                                         "Dapple Dualies",
                                                         "Light Tetra Dualies",
                                                         "Sorella Brella",
                                                         "Tenta Sorella Brella"
                                                        ],
                                      "Booyah Bomb" : [
                                                      "Kensa Splattershot Pro",
                                                      "Aerospray PG",
                                                      "Kensa .52 Gal",
                                                      "Kensa Dynamo Roller",
                                                      "Heavy Splatling Remix"
                                                      ],
                                      "Bubble Blower" : [
                                                         "Forge Splattershot Pro",
                                                         "Kensa Splattershot Jr.",
                                                         "Cherry H-3 Nozzlenose",
                                                         "Foil Squeezer",
                                                         "Custom Range Blaster",
                                                         "Kensa Splat Roller",
                                                         "Custom E-liter 4K",
                                                         "Custom E-liter 4K Scope",
                                                         "Bamboozler 14 Mk 3",
                                                         "Explosher",
                                                         "Heavy Splatling Deco",
                                                         "Tenta Brella"
                                                        ],
                                      "Ink Armor" : [
                                                     "Splattershot Jr.",
                                                     "N-Zap 85",
                                                     ".96 Gal",
                                                     "H-3 Nozzlenose D",
                                                     "Rapid Blaster Pro Deco",
                                                     "Gold Dynamo Roller",
                                                     "Permanent Inkbrush",
                                                     "Classic Squiffer",
                                                     "Tri-Slosher",
                                                     "Custom Hydra Splatling",
                                                     "Kensa Glooga Dualies",
                                                     "Kensa Undercover Brella"
                                                    ],
                                      "Ink Storm" : [
                                                     "Splattershot Pro",
                                                     "Custom Splattershot Jr.",
                                                     "N-Zap 83",
                                                     "Kensa Luna Blaster",
                                                     "Rapid Blaster Pro",
                                                     "Range Blaster",
                                                     "Carbon Roller",
                                                     "E-liter 4K",
                                                     "E-liter 4K Scope",
                                                     "Tri-Slosher Nouveau",
                                                     "Bloblobber",
                                                     "Zink Mini Splatling",
                                                     "Ballpoint Splatling Nouveau",
                                                     "Dapple Dualies Nouveau",
                                                     "Custom Dualie Squelchers",
                                                     "Splat Brella",
                                                     "Hero Brella Replica"
                                                    ],
                                      "Inkjet" : [
                                                  "Tentatek Splattershot",
                                                  "Octo Shot Replica",
                                                  "Splash-o-matic",
                                                  "L-3 Nozzlenose D",
                                                  "Custom Blaster",
                                                  "Rapid Blaster Deco",
                                                  "Octobrush",
                                                  "Herobrush Replica",
                                                  "Custom Goo Tuber",
                                                  "Fresh Squiffer",
                                                  "Ballpoint Splatling",
                                                  "Nautilus 79",
                                                  "Enperry Splat Dualies",
                                                  "Glooga Dualies"
                                                 ],
                                      "Splashdown" : [
                                                      "Splattershot",
                                                      "Hero Shot Replica",
                                                      ".96 Gal Deco",
                                                      "Sploosh-o-matic",
                                                      "Blaster",
                                                      "Splat Roller",
                                                      "Hero Blaster Replica",
                                                      "Inkbrush",
                                                      "Goo Tuber",
                                                      "Kensa Sloshing Machine",
                                                      "Hydra Splatling",
                                                      "Clear Dapple Dualies",
                                                      "Dark Tetra Dualies",
                                                      "Undercover Brella"
                                                     ],
                                      "Sting Ray" : [
                                                     ".52 Gal Deco",
                                                     "Custom Jet Squelcher",
                                                     "Squeezer",
                                                     "Clash Blaster",
                                                     "Dynamo Roller",
                                                     "Splat Charger",
                                                     "Splatterscope",
                                                     "Hero Charger Replica",
                                                     "Sloshing Machine",
                                                     "Heavy Splatling",
                                                     "Hero Splatling Replica"
                                                    ],
                                      "Tenta Missles" : [
                                                         "Kensa Splattershot",
                                                         "N-Zap 89",
                                                         "Jet Squelcher",
                                                         "H-3 Nozzlenose",
                                                         "Neo Sploosh-o-matic",
                                                         "Clash Blaster Neo",
                                                         "Grim Range Blaster",
                                                         "Foil Flingza Roller",
                                                         "Octobrush Nouveau",
                                                         "Bamboozler 14 Mk 1",
                                                         "Slosher",
                                                         "Hero Slosher Replica",
                                                         "Mini Splatling",
                                                         "Splat Dualies",
                                                         "Hero Dualie Replicas",
                                                         "Dualie Squelchers"
                                                        ],
                                      "Ultra Stamp" : [
                                                      "Kensa L-3 Nozzlenose",
                                                      "Sploosh-o-matic 7",
                                                      "Kensa Octobrush",
                                                      "Kensa Mini Splatling",
                                                      "Tenta Camo Brella"
                                                      ]
                                    }
                         }