weapon_info_dict = {
    "Zink Mini Splatling": ["Curling Bombs", "Ink Storm"],
    "Undercover Sorella Brella": ["Splat Bombs", "Baller"],
    "Undercover Brella": ["Ink Mines", "Splashdown"],
    "Tri-Slosher Nouveau": ["Splat Bombs", "Ink Storm"],
    "Tri-Slosher": ["Burst Bombs", "Ink Armor"],
    "Tentatek Splattershot": ["Splat Bombs", "Inkjet"],
    "Tenta Sorella Brella": ["Splash Walls", "Curling-Bomb Launcher"],
    "Tenta Camo Brella": ["Ink Mines", "Ultra Stamp"],
    "Tenta Brella": ["Squid Beakons", "Bubble Blower"],
    "Squeezer": ["Splash Walls", "Sting Ray"],
    "Sploosh-o-matic 7": ["Splat Bombs", "Ultra Stamp"],
    "Sploosh-o-matic": ["Curling Bombs", "Splashdown"],
    "Splattershot Pro": ["Point Sensors", "Ink Storm"],
    "Splattershot Jr.": ["Splat Bombs", "Ink Armor"],
    "Splattershot": ["Burst Bombs", "Splashdown"],
    "Splatterscope": ["Splat Bombs", "Sting Ray"],
    "Splat Roller": ["Curling Bombs", "Splashdown"],
    "Splat Dualies": ["Burst Bombs", "Tenta Missiles"],
    "Splat Charger": ["Splat Bombs", "String Ray"],
    "Splat Brella": ["Sprinklers", "Ink Storm"],
    "Spash-o-matic": ["Toxic Mist", "Inkjet"],
    "Sorella Brella": ["Autobombs", "Splat-Bomb Launcher"],
    "Soda Slosher": ["Splat Bombs", "Burst-Bomb Launcher"],
    "Sloshing Machine Neo": ["Point Sensors", "Splat-Bomb Launcher"],
    "Sloshing Machine": ["Autobombs", "Sting Ray"],
    "Slosher Deco": ["Sprinklers", "Ballers"],
    "Slosher": ["Suction Bombs", "Tenta Missiles"],
    "Rapid Blaster Pro Deco": ["Splash Walls", "Ink Armor"],
    "Rapid Blaster Pro": ["Toxic Mist", "Ink Storm"],
    "Rapid Blaster Deco": ["Suction Bombs", "Inkjet"],
    "Rapid Blaster": ["Ink Mines", "Splat-Bomb Launcher"],
    "Range Blaster": ["Suction Bombs", "Ink Storm"],
    "Permanent Inkbrush": ["Sprinklers", "Ink Armor"],
    "Octo Shot Replica": ["Splat Bombs", "Inkjet"],
    "Octobrush Nouveau": ["Squid Beakons", "Tenta Missiles"],
    "Octobrush": ["Autobombs", "Inkjet"],
    "New Squiffer": ["Autobombs", "Baller"],
    "Neo Splash-o-matic": ["Burst Bombs", "Suction-Bomb Launcher"],
    "Neo Sploosh-o-matic": ["Squid Beakons", "Tenta Missiles"],
    "Nautilus 79": ["Suciton Bombs", "Inkjet"],
    "Nautilus 47": ["Point Sensors", "Baller"],
    "N-Zap 89": ["Autobombs", "Tenta Missiles"],
    "N-Zap 85": ["Suction Bombs", "Ink Armor"],
    "N-Zap 83": ["Sprinklers", "Ink Storm"],
    "Mini Splatling": ["Burst Bombs", "Tenta Missiles"],
    "Luna Blaster Neo": ["Ink Mines", "Suction-Bomb Launcher"],
    "Luna Blaster": ["Splat Bombs", "Baller"],
    "Light Tetra Dualies": ["Sprinklers", "Auto-Bomb Launcher"],
    "L-3 Nozzlenose D": ["Burst Bombs", "Inkjet"],
    "L-3 Nozzlenose": ["Curling Bombs", "Baller"],
    "Krak-On Splat Roller": ["Squid Beakons", "Baller"],
    "Kensa Undercover Brella": ["Torpedoes", "Ink Armor"],
    "Kensa Splattershot Pro": ["Splat Bombs", "Booyah Bomb"],
    "Kensa Splattershot Jr.": ["Torpedoes", "Bubble Blower"],
    "Kensa Splattershot": ["Suction Bombs", "Tenta Missiles"],
    "Kensa Splatterscope": ["Sprinklers", "Baller"],
    "Kensa Splat Roller": ["Splat Bombs", "Bubble Blower"],
    "Kensa Splat Dualies": ["Suction Bombs", "Baller"],
    "Kensa Sloshing Machine": ["Fizzy Bombs", "Splashdown"],
    "Kensa Rapid Blaster": ["Torpedoes", "Baller"],
    "Kensa Octobrush": ["Suction Bombs", "Ultra Stamp"],
    "Kensa Mini Splatling": ["Toxic Mist", "Ultra Stamp"],
    "Kensa Luna Blaster": ["Fizzy Bombs", "Ink Storm"],
    "Kensa L-3 Nozzlenose": ["Splash Walls", "Ultra Stamp"],
    "Kensa Glooga Dualies": ["Fizzy Bombs", "Ink Armor"],
    "Kensa Dynamo Roller": ["Sprinklers", "Booyah Bomb"],
    "Kensa Charger": ["Sprinklers", "Baller"],
    "Kensa .52 Gal": ["Splash Walls", "Booyah Bomb"],
    "Jet Squelcher": ["Toxic Mist", "Tenta Missiles"],
    "Inkbrush Nouveau": ["Ink Mines", "Baller"],
    "Inkbrush": ["Splat Bombs", "Splashdown"],
    "Hydra Splatling": ["Autobombs", "Splashdown"],
    "Herobrush Replica": ["Autobombs", "Inkjet"],
    "Hero Splatling Replica": ["Sprinklers", "Sting Ray"],
    "Hero Slosher Replica": ["Suction Bombs", "Tenta Missiles"],
    "Hero Shot Replica": ["Burst Bombs", "Splashdown"],
    "Hero Roller Replica": ["Curling Bombs", "Splashdown"],
    "Hero Dualie Replicas": ["Burst Bombs", "Tenta Missiles"],
    "Hero Charger Replica": ["Splat Bombs", "Sting Ray"],
    "Hero Brella Replica": ["Sprinklers", "Ink Storm"],
    "Hero Blaster Replica": ["Toxic Mist", "Splashdown"],
    "Heavy Splatling Remix": ["Point Sensors", "Booyah Bomb"],
    "Heavy Splatling Deco": ["Splash Walls", "Bubble Blower"],
    "Heavy Splatling": ["Sprinklers", "Sting Ray"],
    "H-3 Nozzlenose D": ["Suction Bombs", "Ink Armor"],
    "H-3 Nozzlenose": ["Point Sensors", "Tenta Missiles"],
    "Grim Range Blaster": ["Burst Bombs", "Tenta Missiles"],
    "Goo Tuber": ["Suction Bombs", "Splashdown"],
    "Gold Dynamo Roller": ["Splat Bombs", "Ink Armor"],
    "Glooga Dualies Deco": ["Splash Walls", "Baller"],
    "Glooga Dualies": ["Ink Mines", "Inkjet"],
    "Fresh Squiffer": ["Suction Bombs", "Inkjet"],
    "Forge Splattershot Pro": ["Suction Bombs", "Bubble Blower"],
    "Foil Squeezer": ["Splat Bombs", "Bubble Blower"],
    "Foil Flingza Roller": ["Suction Bombs", "Tenta Missiles"],
    "Flingza Roller": ["Splash Walls", "Splat-Bomb Launcher"],
    "Firefin Splatterscope": ["Splash Walls", "Suction-Bomb Launcher"],
    "Firefin Splat Charger": ["Splash Walls", "Suction-Bomb Launcher"],
    "Explosher": ["Sprinklers", "Bubble Blower"],
    "Enperry Splat Dualies": ["Curling Bombs", "Inket"],
    "E-liter 4K Scope": ["Ink Mines", "Ink Storm"],
    "E-liter 4K": ["Ink Mines", "Ink Storm"],
    "Dynamo Roller": ["Ink Mines", "Sting Ray"],
    "Dualie Squelchers": ["Point Sensors", "Tenta Missiles"],
    "Dark Tetra Dualies": ["Autobombs", "Splashdown"],
    "Dapple Dualies Nouveau": ["Toxic Mist", "Ink Storm"],
    "Dapple Dualies": ["Squid Beakons", "Suction-Bomb Launcher"],
    "Custom Splattershot Jr.": ["Autobombs", "Ink Storm"],
    "Custom Range Blaster": ["Curling Bombs", "Bubble Blower"],
    "Custom Jet Squelcher": ["Burst Bombs", "Sting Ray"],
    "Custom Hydra Splatling": ["Ink Mines", "Ink Armor"],
    "Custom Goo Tuber": ["Curling Bombs", "Inkjet"],
    "Custom Explosher": ["Point Sensors", "Baller"],
    "Custom E-liter 4k Scope": ["Squid Beakons", "Bubble Blower"],
    "Custom E-liter 4K": ["Squid Beakons", "Bubble Blower"],
    "Custom Dualie Squelchers": ["Splat Bombs", "Ink Storm"],
    "Custom Blaster": ["Autobombs", "Inket"],
    "Clear Dapple Dualies": ["Torpedoes", "Splashdown"],
    "Classic Squiffer": ["Pont Sensors", "Ink Armor"],
    "Clash Blaster Neo": ["Curling Bombs", "Tenta Missiles"],
    "Clash Blaster": ["Splat Bombs", "Sting Ray"],
    "Cherry H-3 Nozzlenose": ["Splash Walls", "Bubble Blower"],
    "Carbon Roller Deco": ["Burst Bombs", "Auto-Bomb Launcher"],
    "Carbon Roller": ["Autobombs", "Ink Storm"],
    "Bloblobber Deco": ["Sprinklers", "Suction-Bomb Launcher"],
    "Bloblobber": ["Splash Walls", "Ink Storm"],
    "Blaster": ["Toxic Mist", "Splashdown"],
    "Bamboozler 14 Mk 3": ["Fizzy Bombs", "Bubble Blower"],
    "Bamboozler 14 Mk 2": ["Toxic Mist", "Burst-Bomb Launcher"],
    "Bamboozler 14 Mk 1": ["Curling Bombs", "Tenta Missiles"],
    "Ballpoint Splatling Nouveau": ["Squid Beakons", "Ink Storm"],
    "Ballpoint Splatling": ["Toxic Mist", "Inket"],
    "Aerospray RG": ["Sprinklers", "Baller"],
    "Aerospray PG": ["Burst Bombs", "Booyah Bomb"],
    "Aerospray MG": ["Suction Bombs", "Curling-Bomb Launcher"],
    ".96 Gal Deco": ["Splash Walls", "Splashdown"],
    ".96 Gal": ["Sprinklers", "Ink Armor"],
    ".52 Gal Deco": ["Curling Bombs", "Sting Ray"],
    ".52 Gal": ["Point Sensors", "Baller"],
}